HinoDeia/grails-app/controllers/hinodeia/ProdutoEstoqueController.groovy
package hinodeia



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

import org.springframework.security.access.annotation.Secured
@Secured('isFullyAuthenticated()')

@Transactional(readOnly = true)
class ProdutoEstoqueController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond ProdutoEstoque.list(params), model:[produtoEstoqueInstanceCount: ProdutoEstoque.count()]
    }


    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'produtoEstoque.label', default: 'ProdutoEstoque'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

HinoDeia/grails-app/views/produtoEstoque/_form.gsp
<%@ page import="hinodeia.ProdutoEstoque" %>



<div class="fieldcontain ${hasErrors(bean: produtoEstoqueInstance, field: 'quantidade', 'error')} required">
	<label for="quantidade">
		<g:message code="produtoEstoque.quantidade.label" default="Quantidade" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="quantidade" type="number" min="0" value="${produtoEstoqueInstance.quantidade}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: produtoEstoqueInstance, field: 'empreendedor', 'error')} required">
	<label for="empreendedor">
		<g:message code="produtoEstoque.empreendedor.label" default="Empreendedor" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="empreendedor" name="empreendedor.id" from="${hinodeia.Empreendedor.list()}" optionKey="id" required="" value="${produtoEstoqueInstance?.empreendedor?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: produtoEstoqueInstance, field: 'nome', 'error')} required">
	<label for="nome">
		<g:message code="produtoEstoque.nome.label" default="Nome" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="nome" required="" value="${produtoEstoqueInstance?.nome}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: produtoEstoqueInstance, field: 'valor', 'error')} required">
	<label for="valor">
		<g:message code="produtoEstoque.valor.label" default="Valor" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="valor" value="${fieldValue(bean: produtoEstoqueInstance, field: 'valor')}" required=""/>

</div>

HinoDeia/grails-app/views/produtoEstoque/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'produtoEstoque.label', default: 'ProdutoEstoque')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-produtoEstoque" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-produtoEstoque" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${produtoEstoqueInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${produtoEstoqueInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:produtoEstoqueInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

HinoDeia/grails-app/views/produtoEstoque/edit.gsp
<%@ page import="hinodeia.ProdutoEstoque" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'produtoEstoque.label', default: 'ProdutoEstoque')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-produtoEstoque" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-produtoEstoque" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${produtoEstoqueInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${produtoEstoqueInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:produtoEstoqueInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${produtoEstoqueInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

HinoDeia/grails-app/views/produtoEstoque/index.gsp
<%@ page import="hinodeia.ProdutoEstoque" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'produtoEstoque.label', default: 'ProdutoEstoque')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-produtoEstoque" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-produtoEstoque" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="quantidade" title="${message(code: 'produtoEstoque.quantidade.label', default: 'Quantidade')}" />
					
						<th><g:message code="produtoEstoque.empreendedor.label" default="Empreendedor" /></th>
					
						<g:sortableColumn property="nome" title="${message(code: 'produtoEstoque.nome.label', default: 'Nome')}" />
					
						<g:sortableColumn property="valor" title="${message(code: 'produtoEstoque.valor.label', default: 'Valor')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${produtoEstoqueInstanceList}" status="i" var="produtoEstoqueInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${produtoEstoqueInstance.id}">${fieldValue(bean: produtoEstoqueInstance, field: "quantidade")}</g:link></td>
					
						<td>${fieldValue(bean: produtoEstoqueInstance, field: "empreendedor")}</td>
					
						<td>${fieldValue(bean: produtoEstoqueInstance, field: "nomejhsdgfj")}</td>
					
						<td>${fieldValue(bean: produtoEstoqueInstance, field: "valor")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${produtoEstoqueInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

HinoDeia/grails-app/views/produtoEstoque/show.gsp
<%@ page import="hinodeia.ProdutoEstoque" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'produtoEstoque.label', default: 'ProdutoEstoque')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-produtoEstoque" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-produtoEstoque" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list produtoEstoque">
			
				<g:if test="${produtoEstoqueInstance?.quantidade}">
				<li class="fieldcontain">
					<span id="quantidade-label" class="property-label"><g:message code="produtoEstoque.quantidade.label" default="Quantidade" /></span>
					
						<span class="property-value" aria-labelledby="quantidade-label"><g:fieldValue bean="${produtoEstoqueInstance}" field="quantidade"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${produtoEstoqueInstance?.empreendedor}">
				<li class="fieldcontain">
					<span id="empreendedor-label" class="property-label"><g:message code="produtoEstoque.empreendedor.label" default="Empreendedor" /></span>
					
						<span class="property-value" aria-labelledby="empreendedor-label"><g:link controller="empreendedor" action="show" id="${produtoEstoqueInstance?.empreendedor?.id}">${produtoEstoqueInstance?.empreendedor?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${produtoEstoqueInstance?.nome}">
				<li class="fieldcontain">
					<span id="nome-label" class="property-label"><g:message code="produtoEstoque.nome.label" default="Nome" /></span>
					
						<span class="property-value" aria-labelledby="nome-label"><g:fieldValue bean="${produtoEstoqueInstance}" field="nome"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${produtoEstoqueInstance?.valor}">
				<li class="fieldcontain">
					<span id="valor-label" class="property-label"><g:message code="produtoEstoque.valor.label" default="Valor" /></span>
					
						<span class="property-value" aria-labelledby="valor-label"><g:fieldValue bean="${produtoEstoqueInstance}" field="valor"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:produtoEstoqueInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${produtoEstoqueInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>